server.port=8084
server.address=0.0.0.0

resilience.external-client.name=payment-external-client

resilience.external-client.circuit-breaker.failure-rate-threshold=50
resilience.external-client.circuit-breaker.slow-call-rate-threshold=50
resilience.external-client.circuit-breaker.slow-call-duration-seconds=2
resilience.external-client.circuit-breaker.sliding-window-size=10
resilience.external-client.circuit-breaker.minimum-number-of-calls=5
resilience.external-client.circuit-breaker.wait-duration-open-seconds=10
resilience.external-client.circuit-breaker.permitted-half-open-calls=3

resilience.external-client.retry.max-attempts=3
resilience.external-client.retry.wait-duration-millis=300
resilience.external-client.retry.fail-after-max-attempts=true

resilience.external-client.rate-limiter.limit-refresh-period-seconds=1
resilience.external-client.rate-limiter.limit-for-period=10
resilience.external-client.rate-limiter.timeout-duration-millis=200

resilience.external-client.time-limiter.timeout-duration-seconds=2
resilience.external-client.time-limiter.cancel-running-future=true

resilience.external-client.executor.pool-size=4
